"""Recetas de extracción desde EDGAR: dónde está cada dato y con qué patrón se lee.
El texto del documento se normaliza a una sola línea con espacios simples (tablas incluidas),
así una fila de tabla "Total | 548.8 | 504.2" queda como "Total 548.8 504.2".
Cada patrón captura el PRIMER número = período corriente (trimestre en 10-Q/6-K, año en 10-K).
Si una empresa cambia el formato de su reporte, el patrón deja de matchear: el dato queda vacío
y la página lo marca, en vez de tomar un número equivocado. Rangos = control de plausibilidad."""

N = r"(\(?-?[\d][\d,]*\.?\d*\)?)"   # número con miles y decimales

RECETAS = {
    "EOG": {"docs": {"periodico": {"descubrir": "submissions", "forms": ["10-Q", "10-K"]},
                     "reservas": {"descubrir": "fts", "q": '"Net Proved Reserves Reconciliation"', "forms": "8-K", "solo_q4": True}},
        "campos": {
            "crudo_kbd":      ("periodico", r"Crude Oil and Condensate Volumes \(MBbld\).{0,200}?Total " + N, (50, 3000)),
            "ngl_kbd":        ("periodico", r"Natural Gas Liquids Volumes \(MBbld\).{0,150}?Total " + N, (0, 2000)),
            "gas_mmcfd":      ("periodico", r"Natural Gas Volumes \(MMcfd\).{0,200}?Total " + N, (0, 20000)),
            "total_kboed":    ("periodico", r"Crude Oil Equivalent Volumes \(MBoed\).{0,200}?Total " + N, (50, 5000)),
            "p_crudo":        ("periodico", r"Average Crude Oil and Condensate Prices \(\$/Bbl\).{0,200}?Composite " + N, (15, 250)),
            "p_ngl":          ("periodico", r"Average Natural Gas Liquids Prices \(\$/Bbl\).{0,80}?United States \$ " + N, (1, 150)),
            "p_gas_mcf":      ("periodico", r"Average Natural Gas Prices \(\$/Mcf\).{0,200}?Composite " + N, (0.1, 30)),
            "lifting_boe":    ("periodico", r"costs per barrel of oil equivalent \(Boe\).{0,200}?Lease and Well \$ " + N, (0.5, 60)),
            "gpt_boe":        ("periodico", r"\(GP&T\) " + N, (0, 40)),
            "ga_boe":         ("periodico", r"General and Administrative \(G&A\) " + N, (0, 20)),
            "dda_boe":        ("periodico", r"\(DD&A\) - Oil and Gas Properties " + N, (1, 60)),
            "toti_musd":      ("periodico", r"Taxes Other Than Income " + N, (0, 50000)),
            "reservas_mmboe": ("reservas", r"(?s).*Ending Reserves [\d,]+ [\d,]+ (?:—|[\d,]+) (?P<v>[\d,]+)", (100, 50000)),
        }},
    "COP": {"docs": {"periodico": {"descubrir": "submissions", "forms": ["10-Q", "10-K"]},
                     "reservas": {"descubrir": "fts", "q": '"year-end proved reserves"', "forms": "8-K", "solo_q4": True}},
        "campos": {
            "crudo_kbd":      ("periodico", r"Average Net Production Crude oil \(MBD\).{0,120}?Total crude oil " + N, (50, 5000)),
            "bitumen_kbd":    ("periodico", r"Bitumen \(MBD\) " + N, (0, 1000)),
            "ngl_kbd":        ("periodico", r"Total natural gas liquids " + N, (0, 3000)),
            "gas_mmcfd":      ("periodico", r"Total natural gas (\d[\d,]*\.?\d*)", (0, 30000)),
            "total_kboed":    ("periodico", r"Total Production \(MBOED\) " + N, (50, 10000)),
            "total_mmboe":    ("periodico", r"Total Production \(MMBOE\) " + N, (1, 5000)),
            "p_crudo":        ("periodico", r"(?i)Average Sales Prices Crude oil \(per BBL\).{0,160}?Total crude oil " + N, (15, 250)),
            "p_ngl":          ("periodico", r"(?i)Natural gas liquids \(per BBL\).{0,160}?Total natural gas liquids " + N, (1, 150)),
            "p_gas_mcf":      ("periodico", r"(?i)Natural gas \(per MCF\).{0,160}?Total natural gas \$? ?" + N, (0.1, 30)),
            "opex_musd":      ("periodico", r"Production and operating expenses " + N, (10, 100000)),
            "sga_musd":       ("periodico", r"Selling, general and administrative expenses " + N, (0, 20000)),
            "toti_musd":      ("periodico", r"Taxes other than income taxes " + N, (0, 50000)),
            "dda_musd":       ("periodico", r"Depreciation, depletion and amortization " + N, (10, 100000)),
            "reservas_mmboe": ("reservas", (r"(?i)year-end (?:total )?proved reserves (?:are|were) " + N + r" billion", 1000), (100, 50000)),
        }},
    "YPF": {"docs": {"release": {"descubrir": "fts", "q": '"Total Lifting Cost"', "forms": "6-K"}},
        "campos": {
            "crudo_kbd":      ("release", r"Crude Oil \(Kbbl/d\) " + N, (50, 2000)),
            "ngl_kbd":        ("release", r"NGL \(Kbbl/d\) " + N, (0, 500)),
            "total_kboed":    ("release", r"Total Production \(Kboed\) " + N, (50, 3000)),
            "p_crudo":        ("release", r"Crude Oil Price \(US\$/bbl\) " + N, (15, 250)),
            "p_gas_mmbtu":    ("release", r"Natural Gas Price \(US\$/MBTU\) " + N, (0.1, 30)),
            "lifting_boe":    ("release", r"Total Lifting Cost \(US\$/boe\) (?:\(\d\) )?" + N, (0.5, 60)),
            "regalias_boe":   ("release", r"Royalties and other taxes " + N, (0, 60)),
            "reservas_mmboe": ("release", r"Proved reserves \(P1\) closed in \d{4} at " + N + r" M+boe", (10, 20000)),
            "ebitda_no_up_q": ("release", [r"Adj\. EBITDA Upstream .{0,80}?Midstream & Downstream " + N,
                                           r"EBITDA & CAPEX BY SEGMENT.{0,160}?Downstream " + N], (-5000, 20000)),
        }},
    "VIST": {"docs": {"release": {"descubrir": "fts", "q": '"Total (boe/d)"', "forms": "6-K", "debe_contener": "Lifting cost ($/boe)"}},
        "campos": {
            "total_kboed":    ("release", (r"Total \(boe/d\) " + N, 0.001), (10, 2000)),
            "crudo_kbd":      ("release", (r"Oil \(bbl/d\) " + N, 0.001), (10, 2000)),
            "p_crudo":        ("release", r"Oil \(\$/bbl\) (?:\(\d\) )?" + N, (15, 250)),
            "p_gas_mmbtu":    ("release", r"Natural Gas \(\$/MMBTU\) " + N, (0.1, 30)),
            "lifting_boe":    ("release", r"Lifting cost \(\$/boe\) " + N, (0.5, 60)),
            "regalias_kusd":  ("release", r"Royalties and others \(?" + N, (0, 5000000)),
            "ingresos_musd":  ("release", r"Total revenues in Q\d \d{4} were " + N + r" \$MM", (1, 50000)),
            "reservas_mmboe": ("release", r"Total proved reserves as of December 31, \d{4}, totaled " + N + r" MMboe", (10, 20000)),
        }},
    "PBR": {"docs": {"reservas": {"descubrir": "fts", "q": '"Proved Reserves"', "forms": "6-K", "solo_q4": True, "debe_contener": "barrels of oil equivalent"},
                     "resultados": {"descubrir": "fts", "q": '"Lifting cost Brazil"', "forms": "6-K"},
                     "produccion": {"descubrir": "fts", "q": ['"Total commercial production"', '"Crude oil and NGLs"', '"production of oil, NGL and natural gas"'], "forms": "6-K", "debe_contener": "(Mboed)"}},
        "campos": {
            "crudo_kbd":      ("produccion", r"(?i)Crude oil and NGLs \(mbpd\) ?(?:\(\d\) )?" + N, (100, 10000)),
            "brasil_kboed":   ("produccion", r"(?i)Crude oil, NGL and natural gas production - Brazil \(mboed\) " + N, (100, 10000)),
            "gas_kboed":      ("produccion", r"(?i)Natural gas \(Mboed\) " + N, (0, 5000)),
            "total_kboed":    ("produccion", [r"(?i)Total production \(mboed\) " + N,
                                                 (r"Total own production in [1-4]Q\d\d: " + N + r" million boed", 1000)], (100, 10000)),
            "reservas_mmboe": ("reservas", (r"estimated at " + N + r" billion barrels of oil equivalent", 1000), (100, 50000)),
            "lifting_boe":    ("resultados", r"Lifting cost Brazil \(US\$/boe\) " + N, (0.5, 60)),
            "lifting_pt_boe": ("resultados", r"Lifting cost \+ Production taxes " + N, (0.5, 150)),
            "brent_q":        ("resultados", r"Brent crude \(US\$/bbl\) " + N, (15, 250)),
            "ebitda_rtm_q":   ("resultados", [r"RTM RESULTS.{0,900}?Adjusted EBITDA of the segment " + N,
                                              r"Adjusted EBITDA of the segment [\d,\.\(\)]+ .{0,8000}?Adjusted EBITDA of the segment " + N], (-20000, 50000)),
            "ebitda_glce_q":  ("resultados", [r"G&LCE RESULTS.{0,900}?Adjusted EBITDA of the segment " + N,
                                              r"Adjusted EBITDA of the segment [\d,\.\(\)]+ .{0,8000}?Adjusted EBITDA of the segment [\d,\.\(\)]+ .{0,8000}?Adjusted EBITDA of the segment " + N], (-5000, 20000)),
            "p_gas_boe":      ("resultados", r"Natural gas sales price - Brazil \(US\$/bbl\) " + N, (1, 200)),
        }},
    # PRIO no es registrante SEC: no hay EDGAR. Se cubre con CVM + yfinance + semillas citadas.
}
